---

- hosts: master
  become: true
  become_user: root
  tasks:

  # Install Docker and its dependent components.
  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version of docker
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
      state: present

  - name: Install docker and its dependecies
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    notify:
      - docker status

  - name: Get jenkins key
    shell: curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null

  - name: Add apt repository for LTS versions of jenkins
    apt_repository:
      repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ 
      state: present


  - name: Install python-pip java-11
    apt: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - python3-pip 
      - openjdk-11-jdk
      

  - name: Install jenkins
    apt: 
      name:  jenkins
      state: present
      update_cache: yes

  # Install (Docker) python package.
  - name: Install Docker python package
    pip:
      name: docker

  - name: Add ubuntu user to docker group
    user:
      name: ubuntu
      group: docker
  
  - name: Restart docker
    service:
      name: docker
      enabled: yes
      daemon_reload: yes
      state: restarted 

  - name: Pull nginx docker image
    docker_image:
      name: nginx
      source: pull
      
  - name: Print initial jenkins password
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    register : jenkinspassword

  - debug:
      var: jenkinspassword.stdout

  - name: Add jenkins user to docker group
    user:
      name: jenkins
      group: docker

  - name: Restart Jenkins
    service:
      name: jenkins
      enabled: yes
      daemon_reload: yes
      state: restarted

   #Setup a handler for checking Docker daemon using the below code.
  handlers:
    - name: docker status
      service: name=docker state=started

  